{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opencost.fullname" . }}
  namespace: {{ include "opencost.namespace" . }}
  labels:
    {{- include "opencost.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "opencost.selectorLabels" . | nindent 4 }}
  type: LoadBalancer
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: 80                # External port on the LoadBalancer
      targetPort: 9090        # Internal port (application port for UI/API)
      protocol: TCP
    - name: http-ui
      port: 81                # External port for UI
      targetPort: 9090        # Internal UI port
      protocol: TCP
    {{- if .Values.opencost.exporter.debugPort }}
    - name: debug-port
      port: {{ .Values.opencost.exporter.debugPort }}
      targetPort: {{ .Values.opencost.debugPort }}
      protocol: TCP
    {{- end }}
    {{- with .Values.service.extraPorts }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}

